# Generated by Django 4.1 on 2023-01-09 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("addresses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="users",
            field=models.ManyToManyField(
                related_name="addresses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
