# Generated by Django 4.1 on 2023-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_initial"),
        ("addresses", "0003_alter_address_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="sellers",
            field=models.ManyToManyField(related_name="Addresses", to="sellers.seller"),
        ),
    ]
