# Generated by Django 4.1 on 2023-01-09 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sellers", "0002_initial"),
        ("addresses", "0004_address_sellers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="sellers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="Addresses", to="sellers.seller"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
