# Generated by Django 4.1 on 2023-01-11 21:56


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_payment",
                    models.CharField(
                        choices=[
                            ("Pix", "Pix"),
                            ("Card", "Card"),
                            ("Not informed", "Default"),
                        ],
                        default="Not informed",
                        max_length=30,
                    ),
                ),
                ("total_price", models.FloatField()),
                ("done", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
