# Generated by Django 4.1 on 2023-01-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
