# Generated by Django 4.1.4 on 2023-01-09 04:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("undeleted_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
