# Generated by Django 4.1 on 2023-01-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
