services:
  e-commerce_db:
    image: postgres
    env_file: .env
    ports:
      - 5444:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5

  migrations:
    build: .
    command: python manage.py migrate
    depends_on: 
      e-commerce_db:
        condition: service_healthy

  e-commerce:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      e-commerce_db:
        condition: service_healthy
      migrations: 
        condition: service_completed_successfully