# Generated by Django 4.1.4 on 2023-01-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category_product",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
