# Generated by Django 4.1.4 on 2023-01-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories_products", "0002_category_product_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category_product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
