# Generated by Django 4.1.4 on 2023-01-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sellers",
            field=models.ManyToManyField(related_name="products", to="sellers.seller"),
        ),
    ]
