# Generated by Django 4.1.4 on 2023-01-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
