# Generated by Django 4.1.4 on 2023-01-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0004_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="clients",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="products",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="quantity_product",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="subtotal_price",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="orders",
            field=models.ManyToManyField(
                related_name="order_products",
                through="products.OrderProduct",
                to="orders.order",
            ),
        ),
    ]
