# Generated by Django 4.1.4 on 2023-01-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_remove_cart_product_alter_cart_payment"),
        ("products", "0004_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="carts.cart",
            ),
        ),
    ]
