# Generated by Django 4.1.4 on 2023-01-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_orderproduct_clients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="quantity_product",
            field=models.IntegerField(null=True),
        ),
    ]
