# Generated by Django 4.1 on 2023-01-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_quantity_alter_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
