# Generated by Django 4.1 on 2023-01-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        ("products", "0008_remove_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="orders",
            field=models.ManyToManyField(
                related_name="products",
                through="products.OrderProduct",
                to="orders.order",
            ),
        ),
    ]
